spring:
  application:
    name: iToken-zipkin
  boot:
    admin:
      client:
        url: http://127.0.0.1:8084
  zipkin:
    base-url: http://127.0.0.1:9411

server:
  port: 9411

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
