spring:
  application:
    name: iToken-zuul
  zipkin:
    base-url: http://192.168.60.129:9411
  boot:
    admin:
      client:
        url: http://192.168.60.129:8084

server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone : http://192.168.60.129:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: iToken-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: iToken-web-posts

