spring:
  application:
    name: iToken-eureka
  zipkin:
    base-url: http://192.168.60.129:9411
  boot:
    admin:
      client:
        url: http://192.168.60.129:8084

server:
  port: 8761

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: 192.168.60.129
  client:
    # 将自己注册进eureka(集群需要启用)
    register-with-eureka: true
    # 是否从eureka获取注册信息(集群需要启用)
    fetch-registry: true
    service-url:
      # 集群多个逗号分隔
      defaultZone: http://192.168.60.129:8761/eureka/,http://192.168.60.129:8861/eureka/,http://192.168.60.129:8961/eureka/