spring:
  application:
    name: iToken-eureka
  zipkin:
    base-url: http://127.0.0.1:9411
  boot:
    admin:
      client:
        url: http://127.0.0.1:8084

server:
  port: 8761

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    # 将自己注册进eureka(集群需要启用)
    register-with-eureka: true
    # 是否从eureka获取注册信息(集群需要启用)
    fetch-registry: true
    service-url:
      # 集群多个逗号分隔
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/,http://${eureka.instance.hostname}:${server.port}/eureka/,http://${eureka.instance.hostname}:${server.port}/eureka/